name: DropSync
slug: dropsync
description: Peer-to-peer file transfer app for Home Assistant Supervisor
version: "1.0.1"
url: https://wiki.serversatho.me/en/dropsync
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
init: false

ingress: true
ingress_port: 3000
ingress_stream: true
panel_icon: mdi:swap-horizontal-bold
panel_title: DropSync

homeassistant_api: false
host_network: false

ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: DropSync direct access port

options:
  node_env: production
schema:
  node_env: list(production|development)
